# Login user by email and password
POST http://localhost:3006/api/accounts/register HTTP/1.1
Content-Type: application/json

{
  "fullname": "Govard Lavkraft",
  "email": "ruslan4432022@gmail.com",
  "password": "123456"
}

###
# Login user by email and password
POST http://localhost:3006/api/accounts/login HTTP/1.1
Content-Type: application/json

{
  "email": "ruslan4432013@gmail.com",
  "password": "123456"
}

> {%
  client.global.set("auth_token", response.body.accessToken)
  client.global.set("refresh_token", response.body.refreshToken)
%}

###

# Get new JWT pair
GET http://localhost:3006/api/accounts/refresh HTTP/1.1
Authorization: Bearer {{refresh_token}}

###

###
POST http://localhost:3006/api/accounts/change-password
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "currentPassword": "123456789",
  "newPassword": "123456"
}

###
GET http://localhost:3006/api/accounts/65b543ad43af7fe1b3c24afd
Authorization: Bearer {{auth_token}}


###

# Создать публикацию - ссылку
POST http://localhost:3006/api/publications/link HTTP/1.1
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "url": "http://youtube.com/",
  "description": "Tестовое видео, которое больше 45 символов",
  "tags": [
    "json",
    "condo",
    "mandsan"
  ]
}


###
# Upload some file
POST http://localhost:3006/api/files/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="nest_img.jpg"

< ../assets/nest_img.jpg

--boundary--

### Поставить лайк
POST http://localhost:3006/api/likes-publication/like
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "publicationId": "1d090683-3c81-426c-a76e-cf348a2fdd5d"
}

### Создание комментария для публикации
POST http://localhost:3006/api/publications/1d090683-3c81-426c-a76e-cf348a2fdd5d/comments
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "message": "Братан, хорош, давай, давай, вперёд! Контент в кайф, можно ещё? Вообще красавчик! Можно вот этого вот почаще?"
}

### Удаление комментария
DELETE http://localhost:3006/api/publications/1d090683-3c81-426c-a76e-cf348a2fdd5d/comments/48fdb2b0-3842-4011-bbf1-bd4076f5e350
Authorization: Bearer {{auth_token}}

### Получение комментариев
GET http://localhost:3006/api/publications/1d090683-3c81-426c-a76e-cf348a2fdd5d/comments
Authorization: Bearer {{auth_token}}

### Начать рассылку для текущего пользователя
POST http://localhost:3006/api/notify
Authorization: Bearer {{auth_token}}

###
