# Login user by email and password
POST http://localhost:3006/api/accounts/login HTTP/1.1
Content-Type: application/json

{
  "email": "ruslan4432013@gmail.com",
  "password": "123456"
}

> {%
  client.global.set("auth_token", response.body.accessToken)
  client.global.set("refresh_token", response.body.refreshToken)
%}

###
# Получение публикации по ID
GET http://localhost:3006/api/publications/video/ec073f9b-31a0-4a11-aab7-6f76824b5012

###
# Create a video publication
POST http://localhost:3006/api/publications/video HTTP/1.1
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Новое видео, которое больше 40 символов",
  "link": "http://youtube.com/",
  "tags": [
    "boaut",
    "coundars",
    "generator"
  ]
}

###
# Удаление видео-публикации по ID
DELETE http://localhost:3006/api/publications/video/ec073f9b-31a0-4a11-aab7-6f76824b5012
Authorization: Bearer {{auth_token}}

###
# Частичное обновление публикации
PATCH http://localhost:3006/api/publications/video/ec073f9b-31a0-4a11-aab7-6f76824b5012 HTTP/1.1
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Обновленное видео, c корректной ссылкой",
  "link": "http://youtube.com/watch",
  "tags": [
    "boaut",
    "coundars",
    "generator"
  ]
}

###
