# Create a new user
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "fullname": "Smith Adam",
  "password": "123456"
}

###

# Get user by ID
GET http://localhost:3000/api/auth/7fe130bd-f81b-4ff6-b570-cd2726e8c4a4 HTTP/1.1

###

# Login user by email and password
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "password": "123456"
}

###
