# Create a new user
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "fullname": "Smith Adam",
  "password": "123456"
}

###

# Get user by ID
GET http://localhost:3000/api/auth/658a0d56dd3da4d9a131e669 HTTP/1.1

###

# Login user by email and password
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "password": "123456"
}

###
