# Получение публикации по ID
GET http://localhost:3000/api/publications/photo/d0ea9abe-22bc-43ce-a009-e88e5d20c8ae

###
# Create a photo publication
POST http://localhost:3000/api/publications/photo HTTP/1.1
Content-Type: application/json

{
  "photo": "Здесь должно быть фото",
  "ownerId": "659b750fbf3a5865a3ba0862",
  "tags": ["boaut", "coundars", "generator"]
}
###
# Удаление видео-публикации по ID
DELETE http://localhost:3000/api/publications/photo/d4e81b61-57f9-419c-89d7-a41288cfea26

###
# Частичное обновление публикации
PATCH http://localhost:3000/api/publications/photo/d0ea9abe-22bc-43ce-a009-e88e5d20c8ae HTTP/1.1
Content-Type: application/json

{
  "photo": "Здесь другое фото",
  "ownerId": "659b750fbf3a5865a3ba0862",
  "tags": ["boaut", "coundars", "generator"]
}
###
